# Generated by Django 4.2.6 on 2023-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=5)),
                ('costo', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=60)),
                ('cupo', models.IntegerField()),
                ('catedratico', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Curso',
            },
        ),
    ]
