# Generated by Django 4.2.6 on 2023-10-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academiausaccursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
