# Generated by Django 4.2.6 on 2023-10-19 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacionenlinea', '0002_alter_pedidocurso_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedidocurso',
            table='Asignaciones',
        ),
    ]
