version: "3"

services:
  academiausac.ck7yyzhrlc9a.us-east-2.rds.amazonaws.com:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: nicolas37289915
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  django_app:
    build: .
    volumes:
      - static:/code/staticfiles
      - .:/code
    depends_on:
      - academiausac.ck7yyzhrlc9a.us-east-2.rds.amazonaws.com
  
  nginx:
    image: nginx:1.18.0
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d/:/etc/nginx/conf.d
      - static:/code/staticfiles
    depends_on:
      - django_app

volumes:
  .:
  postgres_data:
  static: