# Generated by Django 4.2.6 on 2023-10-18 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catedratico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('DPI', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
                ('contraseniaconfirm', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nombre_de_catedratico',
                'verbose_name_plural': 'Nombre_de_catedraticos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5)),
                ('costo', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=60)),
                ('cupo', models.PositiveIntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursoasignacion')),
                ('disponibilidad', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now_add=True)),
                ('nombrecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursoasignacion.catedratico')),
            ],
            options={
                'verbose_name': 'Nombre_de_curso',
                'verbose_name_plural': 'Nombre_de_cursos',
            },
        ),
    ]
