# Generated by Django 4.2.6 on 2023-10-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursoasignacion', '0002_catedratico_updated_catedratico_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='catedratico_asignado',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='cursoasignacion.catedratico'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombrecurso',
            field=models.CharField(default=True, max_length=80),
        ),
    ]
