# Generated by Django 4.2.6 on 2023-10-19 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursoasignacion', '0003_curso_catedratico_asignado_alter_curso_nombrecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='catedratico_asignado',
            field=models.ForeignKey(default='Nombre de su curso', on_delete=django.db.models.deletion.CASCADE, to='cursoasignacion.catedratico'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo',
            field=models.FloatField(),
        ),
    ]
