# Generated by Django 4.2.6 on 2023-10-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineaasignacion',
            old_name='asignar_id',
            new_name='asignar',
        ),
        migrations.RenameField(
            model_name='lineaasignacion',
            old_name='curso_id',
            new_name='curso',
        ),
    ]
