# Generated by Django 4.2.6 on 2023-10-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='contenido',
            field=models.CharField(max_length=200),
        ),
    ]
